from .inline_buttons import types_materials_inline_keyboard
from .inline_buttons import useful_links_inline_keyboard
from .inline_buttons import interesting_facts_inline_keyboard
from .inline_buttons import link_for_post_inline_keyboard
